### ISSUE TITLE
 Missing installation via a package manager such as fisher

### ISSUE THREAD

**Issue by ubmit** [rose-pine/fish#1]
I think this would make the setup for the theme, easier. If that makes sense, I'd be glad to create a PR for it.

**Comment by mvllow** [comment]
That sounds great! Curious if it would be helpful at all to have three separate themes instead of baking them into one – or perhaps the one file makes it easier

**Comment by ubmit** [comment]
Having they separated would be better for sure!

**Comment by mvllow** [comment]
Great, each variant is now separate :)

Glancing at fisher, it looks like the theme files may need moved – I used our build package to generate them so if you do need to move them please update our build command in the readme, e.g.

```diff
- npx @rose-pine/build -f hex-ns -t ./source.fish -o ./
+ npx @rose-pine/build -f hex-ns -t ./source.fish -o ./conf.d
```

Hopefully `source.fish` (our template to build the variants from) doesn't get in the way.

**Comment by ubmit** [comment]
> Great, each variant is now separate :)
> 
> Glancing at fisher, it looks like the theme files may need moved – I used our build package to generate them so if you do need to move them please update our build command in the readme, e.g.
> 
> ```diff
> - npx @rose-pine/build -f hex-ns -t ./source.fish -o ./
> + npx @rose-pine/build -f hex-ns -t ./source.fish -o ./conf.d
> ```
> 
> Hopefully `source.fish` (our template to build the variants from) doesn't get in the way.

It should be `./themes` instead of `./conf.d`, no?

**Comment by mvllow** [comment]
After reading your PR yes, themes directory seems more appropriate :)
